"""price/number

Revision ID: 474bac2d7c2d
Revises: 17edc7205657
Create Date: 2026-10-01 07:53:27.096864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474bac2d7c2d'
down_revision: Union[str, Sequence[str], None] = '17edc7205657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'ticket_number',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('tickets', 'price')
    # ### end Alembic commands ###
